name: Android APK Build

on:
  workflow_dispatch: # Ungaluku venum borthu manual-ah run panna

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew
      continue-on-error: true

    - name: Build APK Standard Production
      run: ./gradlew assembleDebug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: QC-Workflow-App
        path: app/build/outputs/apk/debug/*.apk
        
